# Generated by Django 4.1 on 2022-08-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('access_date', models.DateTimeField()),
            ],
        ),
    ]
