# Generated by Django 4.1 on 2022-08-25 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('cell_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.storage')),
            ],
        ),
    ]
